SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

DECK_OFFSET = 20
BUTTON_UPPER_OFFSET = 12
BUTTON_LOWER_OFFSET = 52
BUTTON_WIDTH = 75
BUTTON_HEIGHT = 25

CARD_WIDTH = 200
CARD_HEIGHT = 250

HUD_HEIGHT = 300

FIELD_WIDTH = 124
FIELD_HEIGHT = 48
FIELD_GAP = 16
FIELD_OFFSET_Y = SCREEN_HEIGHT - HUD_HEIGHT - 134

ENTITY_Y = SCREEN_HEIGHT // 3 - FIELD_HEIGHT // 2

BUFF_Y = ENTITY_Y - 50

STATS_OFFSET_X = 30
STATS_OFFSET_Y = 60

DESCRIPTION_OFFSET_X = 35
DESCRIPTION_OFFSET_Y = SCREEN_HEIGHT - HUD_HEIGHT - 70

#RPG
PLAYER_WALK_SPEED = 100
